<script lang="ts">
  import type {ReplicaInfo} from '../lib/types';
  export let open = false;
  export let title = '';
  export let items: ReplicaInfo[] = [];
  export let loading = false;
  export let error = '';
</script>
{#if open}<div class="backdrop" role="presentation" on:click={(event) => event.target === event.currentTarget && (open = false)}><div class="modal" role="dialog" aria-modal="true" aria-labelledby="replica-title"><div class="head"><div><p class="card-label">Replica map</p><h2 id="replica-title">{title}</h2></div><button class="icon-button" aria-label="Close account access details" on:click={() => open = false}>×</button></div>{#if loading}<div class="skeleton-stack"><div class="skeleton" style="height:46px"></div><div class="skeleton" style="height:46px"></div></div>{:else if error}<p class="error">{error}</p>{:else if !items.length}<p class="empty">No replica or access records have been registered for this location.</p>{:else}<div class="list">{#each items as item (item.object_id + ':' + item.chunk_order + ':' + item.account_id)}<div class="row"><div><strong>{item.account_label}</strong><small>{item.mode === 'access' ? 'Access-only via shared chat' : 'Physical replica'} · chunk {item.chunk_order + 1}</small></div><span class:access={item.mode === 'access'}>{item.state}</span></div>{/each}</div><p class="fine-print">Round-robin reads use the primary location and ready physical replicas. Access-only records require that account to see the source group.</p>{/if}</div></div>{/if}
<style>
  .backdrop{position:fixed;inset:0;z-index:30;display:grid;place-items:center;padding:20px;background:rgba(12,25,42,.58)}.modal{width:min(620px,100%);max-height:calc(100vh - 40px);overflow:auto;padding:22px;border:1px solid var(--border);border-radius:var(--radius-lg);background:var(--surface);box-shadow:0 20px 60px rgba(13,31,52,.25)}.head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.head h2{margin:.25rem 0 1rem;color:#203b57;overflow-wrap:anywhere}.icon-button{width:36px;height:36px;padding:0;border-radius:50%;background:var(--accent-soft);color:var(--text);font-size:1.35rem}.list{display:grid;gap:8px}.row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px;border:1px solid #e0eaf1;border-radius:12px;background:#fbfdff}.row div{display:grid;gap:3px}.row small{color:var(--muted);font-size:.72rem}.row span{padding:5px 9px;border-radius:999px;background:#e3f5e9;color:#17604a;font-size:.7rem;font-weight:800}.row span.access{background:#eaf0fb;color:#3b5a8e}.empty,.error{padding:24px 0;color:var(--muted)}.error{color:var(--danger)}
</style>
